package http

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/google/wire"
	"github.com/unchainio/interfaces/logger"

	"bitbucket.org/unchain/ares/gen/api/operations/hello"

	"bitbucket.org/unchain/ares/gen/api"
	"bitbucket.org/unchain/ares/pkg/ares"
	"github.com/go-openapi/runtime/middleware"
)

var _ api.HelloAPI = &HelloHandler{}

var HelloSet = wire.NewSet(NewHelloHandler, wire.Bind(new(api.HelloAPI), new(HelloHandler)))

// NewHelloHandler
func NewHelloHandler(service ares.HelloService, log logger.Logger) *HelloHandler {
	return &HelloHandler{
		service: service,
		log:     log,
	}
}

// HelloHandler is an empty implementation of the api.HelloAPI interface.
type HelloHandler struct {
	service ares.HelloService
	log     logger.Logger
}

// Hello Hello route
func (h *HelloHandler) Hello(params hello.HelloParams) middleware.Responder {
	return &hello.HelloOK{
		ContentType: "text/plain; charset=utf-8",
		Payload:     h.service.Hello(),
	}
}
