apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-snapshots
  namespace: kube-system
spec:
  replicas: 0
  selector:
    matchLabels:
      app: k8s-snapshots
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      serviceAccountName: k8s-snapshots
      containers:
      - name: k8s-snapshots
        image: elsdoerfer/k8s-snapshots:latest
        env:
        - name: DIGITALOCEAN_ACCESS_TOKEN
          value: "84680b1c05af2b94e6ac147b252d4442bc3c993ef0c49a5eb0839b99babf0f6a"
