// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdapterMessage struct {
	Body                 []byte          `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Attributes           map[string]bool `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AdapterMessage) Reset()         { *m = AdapterMessage{} }
func (m *AdapterMessage) String() string { return proto.CompactTextString(m) }
func (*AdapterMessage) ProtoMessage()    {}
func (*AdapterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_a2ad2a18804d23a6, []int{0}
}
func (m *AdapterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdapterMessage.Unmarshal(m, b)
}
func (m *AdapterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdapterMessage.Marshal(b, m, deterministic)
}
func (dst *AdapterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdapterMessage.Merge(dst, src)
}
func (m *AdapterMessage) XXX_Size() int {
	return xxx_messageInfo_AdapterMessage.Size(m)
}
func (m *AdapterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AdapterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AdapterMessage proto.InternalMessageInfo

func (m *AdapterMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *AdapterMessage) GetAttributes() map[string]bool {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type TaggedAdapterMessage struct {
	Tag                  uint64          `protobuf:"varint,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Message              *AdapterMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaggedAdapterMessage) Reset()         { *m = TaggedAdapterMessage{} }
func (m *TaggedAdapterMessage) String() string { return proto.CompactTextString(m) }
func (*TaggedAdapterMessage) ProtoMessage()    {}
func (*TaggedAdapterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_a2ad2a18804d23a6, []int{1}
}
func (m *TaggedAdapterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaggedAdapterMessage.Unmarshal(m, b)
}
func (m *TaggedAdapterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaggedAdapterMessage.Marshal(b, m, deterministic)
}
func (dst *TaggedAdapterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaggedAdapterMessage.Merge(dst, src)
}
func (m *TaggedAdapterMessage) XXX_Size() int {
	return xxx_messageInfo_TaggedAdapterMessage.Size(m)
}
func (m *TaggedAdapterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TaggedAdapterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TaggedAdapterMessage proto.InternalMessageInfo

func (m *TaggedAdapterMessage) GetTag() uint64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *TaggedAdapterMessage) GetMessage() *AdapterMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*AdapterMessage)(nil), "proto.AdapterMessage")
	proto.RegisterMapType((map[string]bool)(nil), "proto.AdapterMessage.AttributesEntry")
	proto.RegisterType((*TaggedAdapterMessage)(nil), "proto.TaggedAdapterMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_a2ad2a18804d23a6) }

var fileDescriptor_message_a2ad2a18804d23a6 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xab, 0x18,
	0xb9, 0xf8, 0x1c, 0x53, 0x12, 0x0b, 0x4a, 0x52, 0x8b, 0x7c, 0x21, 0xf2, 0x42, 0x42, 0x5c, 0x2c,
	0x49, 0xf9, 0x29, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x90, 0x2b, 0x17,
	0x57, 0x62, 0x49, 0x49, 0x51, 0x66, 0x52, 0x69, 0x49, 0x6a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0x2a, 0xc4, 0x24, 0x3d, 0x54, 0xed, 0x7a, 0x8e, 0x70, 0x75, 0xae, 0x79, 0x25, 0x45,
	0x95, 0x41, 0x48, 0x1a, 0xa5, 0x6c, 0xb9, 0xf8, 0xd1, 0xa4, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53,
	0x21, 0x96, 0x71, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x10, 0x8e, 0x15, 0x93, 0x05, 0xa3, 0x52, 0x24, 0x97, 0x48,
	0x48, 0x62, 0x7a, 0x7a, 0x6a, 0x0a, 0x9a, 0x8b, 0x05, 0xb8, 0x98, 0x43, 0x12, 0xd3, 0xc1, 0x66,
	0xb0, 0x04, 0x81, 0x98, 0x42, 0xfa, 0x5c, 0xec, 0x50, 0xef, 0x82, 0x4d, 0xe1, 0x36, 0x12, 0xc5,
	0xea, 0xd8, 0x20, 0x98, 0xaa, 0x24, 0x36, 0xb0, 0xb4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb0,
	0x61, 0x52, 0xa2, 0x26, 0x01, 0x00, 0x00,
}
