# ---
# file: roles/docker/tasks/main.yml

- name: Ensure old versions of docker are uninstalled
  apt:
    state: absent
    update_cache: yes
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
  tags:
    - docker

- name: Ensure support packages are {{ apt_state }}
  apt:
    state: "{{ apt_state }}"
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  tags:
    - docker

- name: Ensure apt key is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Ensure docker repository is present
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
  tags:
    - docker

- name: Ensure docker packages are {{ apt_state }}
  apt:
    state: "{{ apt_state }}"
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags:
    - docker

- name: Ensure docker pip package is {{ pip_state }}
  pip:
    state: "{{ pip_state }}"
    name:
      - docker
  tags:
    - docker
