---
  apiVersion: v1
  kind: Service
  metadata:
    name: tbg-nodes-service
    namespace: kustomize-managed
    labels:
      app.kubernetes.io/name: tbg-nodes
  spec:
    type: NodePort
    ports:
      - name: default
        port: 4000
        protocol: TCP
      - name: epmd
        port: 4369
        protocol: TCP
    selector:
      app.kubernetes.io/name: tbg-nodes
      app.kubernetes.io/component: server 
