version: "3"

services:
  postgres:
    restart: "unless-stopped"
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./scripts/postgres/:/docker-entrypoint-initdb.d"
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: minio server /home/shared
