url = ":8080"

[logger]
    level = "debug"
    format = "text"

[sql]
    driver = "postgres"
    connectionString = "user=postgres password=postgres host=172.18.0.2 port=5432 dbname=tbg_nodes_dev sslmode=disable"
