{
 "title": "Besu Overview",
 "description": "Provides an overview of Besu nodes",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(ethereum_blockchain_height, kubernetes_namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (besu_blockchain_difficulty_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Total Difficulty"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (ethereum_peer_count{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (1/rate(ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[5m]))"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (time() - besu_blockchain_chain_head_timestamp{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (ethereum_best_known_block_number{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name) (ethereum_best_known_block_number{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"} - ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})"
    },
    {
     "expr": "sum by (kubernetes_namespace, kubernetes_pod_name)  (ethereum_peer_count{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"} / ethereum_peer_limit{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}-{{kubernetes_pod_name}}"
    },
    {}
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ethereum_best_known_block_number{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"} - ethereum_blockchain_height{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}  ",
     "legendFormat": "{{kubernetes_namespace}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "CPU Time IRate [{{kubernetes_namespace}}-{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}} [{{kubernetes_namespace}}-{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"}",
     "legendFormat": "{{kubernetes_namespace}}-{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}