apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS51bmNoYWluLmlvIjp7ImF1dGgiOiJjRzl1ZEhWek9tRnpPVGcyT0dFMVdsVnRNVEEzYkE9PSIsInBhc3N3b3JkIjoiYXM5ODY4YTVaVW0xMDdsIiwidXNlcm5hbWUiOiJwb250dXMifX19
kind: Secret
metadata:
  name: registry-unchain-io
  namespace: blockscout-dan2
type: kubernetes.io/dockerconfigjson