apiVersion: v1
kind: Service
metadata:
  name: besu-node
  labels:
    app: node
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: dev-p2p-udp
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: dev-p2p-tcp
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: http
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 8547
      targetPort: 8547
      protocol: TCP
      name: graphql

