apiVersion: v1
kind: Secret
metadata:
  namespace: velero
  name: cloud-credentials
  labels:
    component: velero
stringData:
  digitalocean_token: '{{DIGITALOCEAN_API_TOKEN}}'
  cloud: |
    [default]
      aws_access_key_id={{SPACES_ACCESS_KEY_ID}}
      aws_secret_access_key={{SPACES_SECRET_ACCESS_KEY}}
type: Opaque
