#!/bin/bash
set -eu -o pipefail

SLACK_API_URL=$(vault kv get -format=json passdb/accounts/pontus-do-slack-alertmanager | jq -r '.data.data.API_URL')

cat <<EOF >$1
global: {}
receivers:
- name: default-receiver
  slack_configs:
    - send_resolved: true
      channel: 'alerts-do-pontus'
      api_url: '$SLACK_API_URL'
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
route:
  group_interval: 5m
  group_wait: 10s
  receiver: default-receiver
  repeat_interval: 24h
EOF
