settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  host: 0.0.0.0
  port: 5001
schema:
- name: ares
  path: .
  commands:
    install:
      status: true
#      dir: ./cmd/ares
      method: make install-ares
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
    - yml
    - toml
    ignored_paths:
    - vendor
    - .git
    - .idea
