apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ropsten-nodes-fullsync
  name: synced-ropsten
spec:
  volumeName: synced-ropsten
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
