{
 "title": "Besu Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(besu_blockchain_chain_head_gas_limit, instance)"
   },
   {
    "name": "job",
    "query": "label_values(besu_blockchain_chain_head_gas_limit, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated Sync Time Remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "(time() - besu_blockchain_chain_head_timestamp{instance=~\"$node\", job=~\"$job\"}) / (2 * delta(besu_blockchain_chain_head_timestamp{instance=~\"$node\", job=~\"$job\"}[12h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Time Sync In Last 24 Hours",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(besu_blockchain_chain_head_timestamp{instance=~\"$node\", job=~\"$job\"}[12h]) * 2",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sync Time Behind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - besu_blockchain_chain_head_timestamp{instance=~\"$node\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ethereum_best_known_block_number{instance=~\"$node\", job=~\"$job\"} - ethereum_blockchain_height{instance=~\"$node\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ethereum_blockchain_height{instance=~\"$node\", job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block Head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "besu_blockchain_chain_head_timestamp{instance=~\"$node\", job=~\"$job\"} * 1000 ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=~\"$node\", job=~\"$job\"} + ignoring(area) jvm_memory_bytes_used{area=\"nonheap\", instance=~\"$node\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$node\", job=~\"$job\"}[1m])",
     "legendFormat": "{{node}}, {{gc}}"
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "1/rate(ethereum_blockchain_height{instance=~\"$node\", job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peers connected per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(besu_peers_connected_total{instance=~\"$node\", job=~\"$job\"}[5m]) - sum by (job, instance) (rate(besu_peers_disconnected_total{instance=~\"$node\", job=~\"$job\"}[5m]))",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  }
 ]
}