apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mainnet-nodes
  name: geth-mainnet-default
  annotations:
    # fake it by indicating this is provisioned dynamically, so the system
    # works properly
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
spec:
  storageClassName: do-block-storage
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 80614e69-6e02-11ea-9c19-0a58ac14807b
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mainnet-nodes
  name: geth-mainnet-default
spec:
  volumeName: geth-mainnet-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  