apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
  namespace: kustomize-managed
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: oauth2-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
  namespace: kustomize-managed
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oauth2-proxy
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      affinity:
        podAntiAffinity: # Don't schedule pods on the same node if posssible.
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: oauth2-proxy
              topologyKey: kubernetes.io/hostname
      containers:
      - name: oauth2-proxy
        args:
        - --github-org=unchain
        - --email-domain=*
        - --provider=github
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        envFrom:
          - secretRef:
              name: oauth2-proxy-env
        image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 4180
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 1
          periodSeconds: 2
---
