---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |-
    <source>
      @type tail
      refresh_interval 1
      path  /var/log/containers/*adapter*.log
      exclude_path ["/var/log/containers/fluentd*"]
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      read_from_head true

      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <match **>
      @type elasticsearch
      hosts elastic:9200

      logstash_format true
      logstash_prefix "adapters-local"
      logstash_dateformat  %Y-%m-%d
      type_name  "container_log"

      <buffer>
        @type file
        path /fluentd/etc/buffer/cluster.buffer
        flush_interval 1s
        flush_thread_count 4
      </buffer>

      slow_flush_log_threshold 40.0
    </match>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      hostNetwork: true
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-elasticsearch-1.7
#          command:
#            - "custom-entrypoint.sh"
          env:
            - name: FLUENTD_CONF
              value: ../etc2/fluent.conf
            - name: FLUENT_UID
              value: "0"
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "172.19.0.2"
            - name:  FLUENTD_SYSTEMD_CONF
              value: "disable"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_ELASTICSEARCH_SED_DISABLE
              value: "true"
            # X-Pack Authentication
            # =====================
#            - name: FLUENT_ELASTICSEARCH_USER
#              value: "elastic"
#            - name: FLUENT_ELASTICSEARCH_PASSWORD
#              value: "changeme"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc2/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config

        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
